use crate::plan::{
    connection::plan::ConnectionPlan,
    define::resolved::ResolvedDefines,
    diagnostics::diagnostic::Diagnostic,
    estimation::resource::ResourceEstimations,
    execution::{
        execution_settings::ExecutionSettings, execution_stage::ExecutionStage,
        summary::PlanSummary,
    },
    pipeline::plan::PipelinePlan,
};
use chrono::{DateTime, Utc};
use serde::Serialize;

/// The main migration report generated by `stratum plan` command.
/// This is the presentation/analysis report, distinct from the internal execution plan
/// used by the runtime. It enriches the core plan with diagnostics, estimations,
/// and metadata gathered from database introspection.
#[derive(Serialize, Debug, Clone)]
pub struct MigrationReport {
    // ─── Metadata ────
    /// Unique identifier for this plan
    pub plan_id: String,
    /// When this plan was generated
    pub generated_at: DateTime<Utc>,
    /// Stratum engine version
    pub engine_version: String,
    /// Hash of the SMQL config (for detecting configuration drift)
    pub config_hash: String,
    /// Path to the SMQL config file
    pub config_path: String,

    // ─── Global Settings ────
    /// From `execution { }` block in SMQL
    pub execution_settings: ExecutionSettings,
    /// From `define { }` block - resolved constants with values
    pub defines: ResolvedDefines,
    /// From `connection { }` blocks - all database connections
    pub connections: Vec<ConnectionPlan>,

    // ─── Pipelines ────
    /// From `pipeline { }` blocks - all data migration pipelines
    pub pipelines: Vec<PipelinePlan>,
    /// DAG-resolved execution order (levels that can run in parallel)
    pub execution_order: Vec<ExecutionStage>,

    // ─── Summary ────
    pub summary: PlanSummary,
    pub diagnostics: Vec<Diagnostic>,
    pub estimations: ResourceEstimations,

    // ─── Status ────
    /// Whether this plan can be executed (no blocking errors)
    pub is_executable: bool,

    /// If not executable, the reason why
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blocking_reason: Option<String>,
}
