[package]
name = "smql"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.0"
pest = "2.7.15"
pest_derive = "2.7.15"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde = "1.0.217"
