use serde::Serialize;

/// Summary of data transformations happening in a pipeline.
/// Provides high-level counts for different types of column operations.
#[derive(Serialize, Debug, Clone, Default)]
pub struct DataFlowSummary {
    /// Direct 1:1 column mappings (no transformation)
    pub direct_columns: usize,
    /// Columns that are renamed
    pub renamed_columns: usize,
    /// Columns with computed expressions
    pub computed_columns: usize,
    /// Columns using conditional logic (when/case statements)
    pub conditional_columns: usize,
    /// Columns populated from joins
    pub lookup_columns: usize,
    /// Columns generated by functions (e.g., now(), uuid())
    pub generated_columns: usize,
    /// Source columns that are not mapped to destination
    pub dropped_columns: Vec<String>,
    /// Destination columns that don't exist in source
    pub new_columns: Vec<String>,
    /// Total number of type conversions
    pub type_conversions: usize,
    /// Type conversions that may lose data or precision
    pub unsafe_conversions: usize,
    pub join_count: usize,
    /// Joins that cross database connections (potentially slow)
    pub cross_connection_joins: usize,
    /// Number of validation assertions
    pub assert_count: usize,
    /// Number of validation warnings
    pub warn_count: usize,
}
