[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
smql = { path = "../smql" }
async-trait = "0.1.86"
serde = "1.0.217"
serde_json = "1.0.138"
bigdecimal = "0.4.7"
chrono = { version = "0.4.39", features = ["serde"] }
uuid = { version = "1.13.1", features = ["serde"] }
lazy_static = "1.5.0"
